export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const SAVE_USERS_SUCCESS = 'SAVE_USERS_SUCCESS';
export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS';
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';
